### ISSUE TITLE
Handling socket notification from the node.js server

### ISSUE THREAD

**Issue by neeraj87** [codeforgeek/socket-notification#2]
This is not an issue per-se but just a question on the variation of how to handle the notification from the server.

Here is my case:

I am inserting a record using mysql upon which I need to send notification to other connected users.

This is the code:

**app.js**

```
var http = require('http');
var io = require('socket.io')(http);

io.on('connection', function(socket){
	console.log('a user connected');
	socket.on('new-rec-created', function(){
		//io.emit('a new housekeeping was requested'); // for all
		socket.broadcast.emit('notify everyone'); // for all except me
	});
});
```

**route.js**

```
var http = require('http');
var io = require('socket.io')(http);

connectionPool.getConnection(function(err, connection){
	if(err) {
		winston.log('debug', '------------------------------------ Error: ' + err);
		connection.release();
		return;
	}
	connection.query(queryString, function(err, rows){
		if (err) {
			winston.log('debug', '------------------------------------ Error: ' + err);
		}
		connection.release();
		socket.emit('new-rec-created');
	});
});
```

my public side **main.js** file

```
$(document).ready(function(){
	var socket = io();
	socket.on('notify everyone',function(){
		notifyMe(); //the js desktop notification code
	});
	.
	.
});
```

Couple of issues I am facing:

1. In the html when I use 

` <script src="/socket.io/socket.io.js"></script>` it kept giving me 404 not found error. So finally I had to use the cdn `<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.1/socket.io.js"></script>`

2. In the router it gives me an error saying socket is undefined. If I do io.socket.emit(..) it says Cannot read property emit of undefined.

I dont understand what I am doing wrong. The weird thing is when I start the server the console.log('a user connected') under io.on('connection') is not printed. Any suggestions or advice?

**Comment by Anujraval24** [comment]
add var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io').listen(server);
